sudo: required
language: node_js
node_js: 
  - "node"

script: npm test

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script: 
  - npm install -g @angular/cli
  - npm run install:both